[theme]
base = "dark"
primaryColor = "#00D4FF"
backgroundColor = "#090807"
secondaryBackgroundColor = "#1E222A"
textColor = "#F5EFE2"
font = "sans serif"
[server]
headless = true
port = 8501
address = "0.0.0.0"

[browser]
gatherUsageStats = false